# Docker Compose file for the PDC's Hub Stack
#
#
# Used for collecting aggregate data queries.
#
# Use secondary .YML files for development and add -f YOUR.YML at execution.


database:
  container_name: database
  hostname: database
  image: pdcbc/gateway_db:prod
  restart: always
  log_driver: "syslog"
  volumes:
    - /encrypted/mongo/:/data/db/:rw


gateway:
  container_name: gateway
  hostname: gateway
  image: pdcbc/gateway:prod
  restart: always
  log_driver: "syslog"
  links:
    - database:database
  volumes:
    - /encrypted/ssh/:/home/autossh/.ssh/:rw
  environment:
    - gID=50
    - DOCTOR_IDS=cpsid


oscar:
  container_name: oscar
  hostname: oscar
  image: pdcbc/oscar_e2e:prod
  log_driver: "syslog"
  links:
    - gateway:gateway
  volumes:
    - /encrypted/import/:/e2e/
