---
# Start Gateway containers
- hosts: all
  become: true

  tasks:
    - name: Create Endpoint config.env
      command: cp /hdc/endpoint/config.env-sample /hdc/endpoint/config.env
      args:
        creates: /hdc/endpoint/config.env

    - name: Restart/start Docker
      service:
        name: docker
        state: restarted

    - name: Install pip
      apt:
        name: python-pip
        state: present
        update_cache: yes

    - name: Install Docker-Py
      pip:
        name: docker-py

    - name: Remove blank lines in .env (for Ansible/docker_container bug)
      replace:
        path: /hdc/endpoint/config.env
        regexp: "^$"
        replace: "#"

    - name: Start gateway_db
      docker_container:
        name: gateway_db
        hostname: gateway_db
        image: mongo:3.2.9
        command: --nojournal
        restart_policy: always
        log_driver: syslog
        volumes:
          - /hdc/data/mongo/:/data/db/:rw

    - name: Start gateway
      docker_container:
        name: gateway
        hostname: gateway
        image: hdcbc/gateway:latest
        restart_policy: always
        log_driver: syslog
        volumes:
          - /hdc/data/config/ssh/:/home/autossh/.ssh/:rw
        ports:
          - "3001:3001"
        links:
          - gateway_db:database
        env_file: "/hdc/endpoint/config.env"
