---
# Start Gateway containers
- hosts: all
  become: true

  tasks:
    - name: Create Endpoint config.env
      command: cp /hdc/endpoint/config.env-sample /hdc/endpoint/config.env
      args:
        creates: /hdc/endpoint/config.env

    - name: Restart/start Docker
      service:
        name: docker
        state: restarted

    - name: Install pip
      apt:
        name: python-pip
        state: present
        update_cache: yes

    - name: Install Docker-Py
      pip:
        name: docker-py

    - name: Fire up containers
      command: chdir=/hdc/endpoint make deploy
