---
# Setup and configure Docker
- hosts: all
  become: true
  tasks:

    - name: Install prerequisites
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Install Docker key
      apt_key:
        id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: Install Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    - name: Create non-standard Docker dir
      file:
        path: /hdc/data/docker
        state: directory

    - name: Create symbolic link for Docker dir
      file:
        src: /hdc/data/docker
        dest: /var/lib/docker
        state: link

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Configure Docker directory and download cap
      lineinfile:
        dest: /lib/systemd/system/docker.service
        regexp: ^ExecStart
        line: ExecStart=/usr/bin/dockerd -g /hdc/data/docker -H fd:// --max-concurrent-downloads 1

    - name: Disable Docker autostart
      replace:
        dest: /etc/init/docker.conf
        regexp: '^start on'
        replace: '#start on'

    - name: Install Docker Compose (Xenial/16.04)
      when: ansible_distribution_release == 'xenial'
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Install Docker Compose (Trusty/14.04)
      when: ansible_distribution_release == 'trusty'
      shell: |
        LIST=$( git ls-remote https://github.com/docker/compose | grep "refs/tags" | grep -oP "[0-9]+(\.[0-9]+)+$" )
        while [ $( echo "${LIST}" | grep -v "^$" | wc -l ) -gt 0 ]
        do
          DIGIT=$( echo "${LIST}" | grep -oP "^[0-9]+" | sort -g | tail -n 1 )
          VERSION="${VERSION:-}"."${DIGIT}"
          LIST=$( echo "${LIST}" | grep -P "^${DIGIT}" | sed 's/^[0-9]*\.*//' )
        done
        VERSION=$( echo "${VERSION}" | sed "s/^\.//" )
        echo "${VERSION}"
        #
        curl -o /usr/local/bin/docker-compose -L \
          https://github.com/docker/compose/releases/download/"${VERSION}"/docker-compose-`uname -s`-`uname -m`
        chmod +x /usr/local/bin/docker-compose

    - name: Reload systemd and Start Docker (Xenial/16.04)
      when: ansible_distribution_release == 'xenial'
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker

    - name: Reload systemd and Start Docker (Trusty/14.04)
      when: ansible_distribution_release == 'trusty'
      service:
        name: docker
        state: restarted
