---
# Start Gateway containers
- hosts: all
  become: true

  tasks:
  - name: Install Pip
    apt:
      name: python-pip
      state: present
      update_cache: yes

  - name: Install Docker-Py
    pip:
      name: docker-py

  - name: Pull Docker image
    docker_image:
      name: "{{ item }}"
    with_items:
      - hdcbc/gateway:latest
      - hdcbc/e2e_oscar:latest
      - mongo:3.2.9

  - name: Start gateway_db
    docker_container:
      name: gateway_db
      hostname: gateway_db
      image: mongo:3.2.9
      command: --nojournal
      restart_policy: always
      log_driver: syslog
      volumes:
        - /hdc/data/mongo/:/data/db/:rw

  - name: Ansible/docker_container bug - remove blank lines in .env
    replace:
      path: /hdc/endpoint/config.env
      regexp: "^$"
      replace: "#"

  - name: Start gateway
    docker_container:
      name: gateway
      hostname: gateway
      image: hdcbc/gateway:latest
      restart_policy: always
      log_driver: syslog
      volumes:
        - /hdc/data/config/ssh/:/home/autossh/.ssh/:rw
      ports:
        - "3001:3001"
      links:
        - gateway_db:database
      env_file: "/hdc/endpoint/config.env"
