---
# Setup python for ansible to work
# From https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
- hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python 2.7
      raw: test -e /usr/bin/python ||( apt update && apt install -y python-minimal )
