---
# Setup Exporter account
- hosts: all
  become: true
  tasks:

    - name: Create exporter user
      user:
        name: exporter
        comment: "OSP export account"
        home: /hdc/data/import/
        shell: /bin/bash

    - name: Create folders and set permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: exporter
        group: exporter
        mode: 0775
        recurse: no
      with_items:
        - /hdc/data/import/
        - /hdc/data/import/.ssh/
